name: Test

on: push

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Get code
              uses: actions/checkout@v4

            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install depencencies
              run: npm ci

            - name: Test
              run: npm test
              
